package org.chinasafety.liu.anjiantong.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table CS_INFO.
 */
public class CsInfo implements IChooseItem{

    private String mplid;
    private String mplname;

    public CsInfo() {
    }


    public CsInfo(String mplid, String mplname) {
        this.mplid = mplid;
        this.mplname = mplname;
    }


    public String getMplid() {
        return mplid;
    }

    public void setMplid(String mplid) {
        this.mplid = mplid;
    }

    public String getMplname() {
        return mplname;
    }

    public void setMplname(String mplname) {
        this.mplname = mplname;
    }

    @Override
    public String getItemName() {
        return mplname;
    }

    @Override
    public String getItemId() {
        return mplid;
    }


}
