package org.chinasafety.liu.anjiantong.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table JCB_INFO.
 */
public class JcbInfo implements IChooseItem {

    private String jcbid;
    private String jcbname;

    public JcbInfo() {
    }


    public JcbInfo(String jcbid, String jcbname) {
        this.jcbid = jcbid;
        this.jcbname = jcbname;
    }


    public String getJcbid() {
        return jcbid;
    }

    public void setJcbid(String jcbid) {
        this.jcbid = jcbid;
    }

    public String getJcbname() {
        return jcbname;
    }

    public void setJcbname(String jcbname) {
        this.jcbname = jcbname;
    }

    @Override
    public String getItemName() {
        return jcbname;
    }

    @Override
    public String getItemId() {
        return jcbid;
    }



    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof JcbInfo)) {
            return false;
        }
        JcbInfo info = (JcbInfo) obj;
        return jcbid.equals(info.getJcbid());
    }

    @Override
    public int hashCode() {
        return jcbid == null ? -1 : jcbid.hashCode();
    }
}
