package org.chinasafety.liu.anjiantong.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table SB_INFO.
 */
public class SbInfo implements IChooseItem{

    private String sbid;
    private String sbname;
    private String csid;

    public SbInfo() {
    }


    public SbInfo(String sbid, String sbname, String csid) {
        this.sbid = sbid;
        this.sbname = sbname;
        this.csid = csid;
    }


    public String getSbid() {
        return sbid;
    }

    public void setSbid(String sbid) {
        this.sbid = sbid;
    }

    public String getSbname() {
        return sbname;
    }

    public void setSbname(String sbname) {
        this.sbname = sbname;
    }

    public String getCsid() {
        return csid;
    }

    public void setCsid(String csid) {
        this.csid = csid;
    }


    @Override
    public String getItemName() {
        return sbname;
    }

    @Override
    public String getItemId() {
        return sbid;
    }


}
